name: Backstage Catalog Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Sync templates to Backstage
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"location": "https://github.com/xGANDAx/Demo_Backstage_Templates/"}' \
          http://localhost:7007/api/catalog/entities
